// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "post": {
                "tags": [
                    "users"
                ],
                "summary": "Login",
                "responses": {}
            }
        },
        "/logout": {
            "post": {
                "tags": [
                    "users"
                ],
                "summary": "Logout",
                "responses": {}
            }
        },
        "/me": {
            "get": {
                "tags": [
                    "users"
                ],
                "summary": "Obter dados do usuário logado",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do usuário",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/postings": {
            "get": {
                "tags": [
                    "postings"
                ],
                "summary": "Listar anúncios públicos",
                "responses": {}
            },
            "post": {
                "tags": [
                    "postings"
                ],
                "summary": "Criar anúncio (posting)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do prestador",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/postings/mine": {
            "get": {
                "tags": [
                    "postings"
                ],
                "summary": "Listar meus anúncios",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do prestador",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/postings/{id}": {
            "get": {
                "tags": [
                    "postings"
                ],
                "summary": "Detalhar anúncio público",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Posting ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "patch": {
                "tags": [
                    "postings"
                ],
                "summary": "Atualizar anúncio",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do prestador",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Posting ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/providers/profile": {
            "patch": {
                "tags": [
                    "users"
                ],
                "summary": "Atualizar perfil do prestador",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do prestador",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/users": {
            "post": {
                "tags": [
                    "users"
                ],
                "summary": "Cadastrar usuário",
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Service Finder API",
	Description:      "Plataforma de prestação e busca de serviços.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
